### ISSUE TITLE
mac os adb binary lands in osx-64 folder instead of osx-x64 folder

### ISSUE THREAD

**Issue by kmiterror** [quamotion/adk-nuget#3]
I use this package for my own project and this caught me of guard.
I looked through your code and I don't see why it's happening.

PS Do you plan on releasing a new package with v30 adk tools?

![image](https://user-images.githubusercontent.com/4394164/91550105-514a2a00-e928-11ea-94c0-fe7349000eb2.png)

**Comment by qmfrederik** [comment]
Sorry for taking two years to respond :-), but the v3x packages are online.  I checked and on osx the items should be correctly packaged.  Let me know if you still use these packages and have any issues.

**Comment by kmiterror** [comment]
better late than never :-) thanks for the effort, 
actually I'm still using this, I will verify it next week

**Comment by kmiterror** [comment]
I checked the latest packages 
and the adk-build-tools is fine
the problem still remains with adk-platform-tools
adb file for mac resides in 
`adk-platform-tools\33.0.2\runtimes\osx-64\native`

because it says `osx-64`  those files are not included by nuget IncludeAssets directive.
It should say `osx-x64` (mind the x before 64), then it will match runtime identifier, and it will work the same way as adk-build-tools.

Can you adjust that?
